---
name: Create a Documentation Update Request
description: Use this template for reporting issues or requesting changes to the Gen3 technical docs repo
labels: Documentation Update
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create an issue. Please read the following before posting:

        DO NOT post any Personally Identifiable Information (PII) in a GitHub Issue.  This includes IP address, hostnames, and tokens.

  - type: input
    attributes:
      label: "What section of the documentation are you asking about?"
      description: "Insert GitHub or docs.gen3.org URL"
      placeholder:
    validations:

  - type: dropdown
    id: occurs_every_time
    attributes:
      label: "Are you willing to and have the technical expertise to submit a PR that addresses this issue?"
      description: "Answer whether you are able to address with a PR"
      options:
        - "Yes"
        - "No"

  - type: textarea
    attributes:
      label: "Describe the issue with the documentation. This could be an error, missing content, or something that is out of date."
      description: "Describe the issue"
      placeholder:
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Include what the updated documentation should look like. Provide as much detail as possible."
